### ISSUE TITLE
Support for google.protobuf.Struct fields.

### ISSUE THREAD

**Issue by shanipribadi** [gojekfarm/beast#13]
Add support for googleprotobuf.Struct fields.

How we can map a message with dynamic schema to a bigquery column.

**Comment by devdinu** [comment]
@shanipribadi `Struct` field is converted to `String` for now. 

Using
```
JsonFormat.printer()
     .omittingInsignificantWhitespace()
     .print((DynamicMessage) fieldValue);
```
